Update client.py
Update CSV reader to use universal-newline mode.

Created CSV file on Mac OSX, kept getting the following error:
```javascript
Traceback (most recent call last):
  File "csv2youtrack.py", line 216, in <module>
    main()
  File "csv2youtrack.py", line 29, in main
    csv2youtrack(source_file, target_url, target_login, target_password, comments_file, attachments_file)
  File "csv2youtrack.py", line 40, in csv2youtrack
    source = Client(source_file)
  File "/Volumes/tempb/SNAPLab/youtrack-client/python/csvClient/client.py", line 8, in __init__
    self._header = self._read_header()
  File "/Volumes/tempb/SNAPLab/youtrack-client/python/csvClient/client.py", line 11, in _read_header
    header = self._get_reader().next()
_csv.Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
```

By updating the open call to use `rU` instead of just `r`, files on Mac OSX successfully processed.